default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 10 } %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  port: <%= ENV.fetch("POSTGRESQL_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRESQL_DATABASE'] %>

test:
  <<: *default
  database: sq_ecommerce_test
